kind = "api"
previewPath = "/"
title = "Taylor Dahlgren Portfolio"
version = "1.0.0"
id = "3B4_FFSkEVBkAeYMFRJ2e"

[[services]]
localPort = 5000
name = "Jekyll Preview"
paths = ["/"]

[services.development]
run = "cd ../.. && bundle exec jekyll serve --host 0.0.0.0 --port 5000"